// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_opened_first_skill_container = "CgkI0uT8k-QUEAIQAw"; // <GPGSID>
        public const string achievement_collect_100000_points = "CgkI0uT8k-QUEAIQCQ"; // <GPGSID>
        public const string achievement_collect_20000_points = "CgkI0uT8k-QUEAIQCA"; // <GPGSID>
        public const string achievement_donate_level_one = "CgkI0uT8k-QUEAIQDg"; // <GPGSID>
        public const string achievement_first_using_ads = "CgkI0uT8k-QUEAIQCw"; // <GPGSID>
        public const string achievement_open_all_containers = "CgkI0uT8k-QUEAIQEQ"; // <GPGSID>
        public const string achievement_donate_level_two = "CgkI0uT8k-QUEAIQDw"; // <GPGSID>
        public const string achievement_collect_5000_points = "CgkI0uT8k-QUEAIQBw"; // <GPGSID>
        public const string achievement_donate_level_three = "CgkI0uT8k-QUEAIQEA"; // <GPGSID>
        public const string achievement_disable_ads = "CgkI0uT8k-QUEAIQDA"; // <GPGSID>
        public const string leaderboard_levels_leaderboard = "CgkI0uT8k-QUEAIQAQ"; // <GPGSID>
        public const string achievement_collect_multiply_points = "CgkI0uT8k-QUEAIQCg"; // <GPGSID>
        public const string achievement_firs_using_ads = "CgkI0uT8k-QUEAIQBA"; // <GPGSID>                      /////////////////// Don`t using!!!
        public const string achievement_first_buy_points = "CgkI0uT8k-QUEAIQDQ"; // <GPGSID>
        public const string achievement_collect_1000_points = "CgkI0uT8k-QUEAIQBg"; // <GPGSID>
        public const string leaderboard_points_leaderboard = "CgkI0uT8k-QUEAIQEg"; // <GPGSID>

}

